apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-produits
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestion-produits
  template:
    metadata:
      labels:
        app: gestion-produits
    spec:
      containers:
      - name: gestion-produits
        image: gestion-produits:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-produits-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gestion-produits
